import Head from "next/head";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";
import Header from "../components/Header.js";
import data from "../mock_data/products.json";
import { useEffect, useState } from "react";
import Basket from "../components/Basket";

const Cart = () => {
  const [cartItems, setCartItems] = useState([]);
  const { products } = data;
  const onAdd = (product) => {
    const exist = cartItems.find((x) => x.sku === product.sku);
    if (exist) {
      const newCartItems = cartItems.map((x) =>
        x.sku === product.sku ? { ...exist, qty: exist.qty + 1 } : x
      );
      setCartItems(newCartItems);
    } else {
      const newCartItems = [...cartItems, { ...product, qty: 1 }];
      setCartItems(newCartItems);
      localStorage.setItem("cartItems", JSON.stringify(newCartItems));
    }
  };

  const onRemove = (product) => {
    const exist = cartItems.find((x) => x.sku === product.sku);
    if (exist.qty === 1) {
      const newCartItems = cartItems.filter((x) => x.sku !== product.sku);
      setCartItems(newCartItems);
      localStorage.setItem("cartItems", JSON.stringify(newCartItems));
    } else {
      const newCartItems = cartItems.map((x) =>
        x.sku === product.sku ? { ...exist, qty: exist.qty - 1 } : x
      );
      setCartItems(newCartItems);
      localStorage.setItem("cartItems", JSON.stringify(newCartItems));
    }
  };

  useEffect(() => {
    setCartItems(
      localStorage.getItem("cartItems")
        ? JSON.parse(localStorage.getItem("cartItems"))
        : []
    );
  }, []);

  return (
    <div>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main products={data} onAdd={onAdd} className={styles.main}>
        {/* Feed display - Flex Grid */}
        <div className="w-full flex flex-wrap bg-grey-light justify-center">
          <Basket cartItems={cartItems} onAdd={onAdd} onRemove={onRemove} />
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Cart;
